baseURL = "https://artikel-le-1.vercel.app/" # We will update this after Vercel deployment
languageCode = "id-id"
title = "Tofu Systems"
theme = "PaperMod"

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = false # Clean look
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  
  [params.profileMode]
    enabled = true
    title = "Tofu Systems"
    subtitle = "Analysis & Engineering Portfolio"
    # If you want a picture, put 'avatar.jpg' in the 'static' folder and uncomment below
    # imageUrl = "avatar.jpg"
    
[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "posts"
    name = "Assignments"
    url = "/posts/"
    weight = 20