baseURL = "https://artikel-le-1.vercel.app/"
languageCode = "id-id"
title = "Selamat Datang di Artikel Milik Saya Hehehe"
theme = "PaperMod"

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = false # Clean look
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  
  [params.profileMode]
    enabled = true
    title = "Artikel Hihihi"
    subtitle = "Analysis & Engineering Portfolio"
    
[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "posts"
    name = "Assignments"
    url = "/posts/"
    weight = 20